language: node_js
node_js:
  - 14
cache:
  directories:
  - node_modules 
script:
  - yarn build 
  - yarn export
  - touch out/.nojekyll
deploy:
  provider: pages 
  skip_cleanup: true
  github_token: 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
  local_dir: out 
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$